version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - revive
    - govet
    - staticcheck

formatters:
  enable:
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
