services:
  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - ./post-service/.env      # Переменные окружения для БД
    ports:
      - "5432:5432"              # внешний порт 5433 для хоста, внутри контейнера 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      # Сколько раз Docker попытается выполнить тест, прежде чем считать контейнер unhealthy
      retries: 5

  post-service:
    build: ./post-service
    env_file:
      - ./post-service/.env
    environment:
      - APP_ENV=dev
    ports:
      - "8000:8000"
      - '2112:2112'
    networks:
      - monitoring
    command: ["sh", "-c", "./migrator --migrations-path ./migrations && ./post-service"]
    depends_on:
      postgres: # Ждем пока health у postgres будет пройден
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  jaeger:
    image: jaegertracing/jaeger:2.16.0
    container_name: jaeger
    ports:
      - "16686:16686"   # UI
      - "4317:4317"     # OTLP receiver
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - JAEGER_COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - monitoring
  notification-service:
    build: ./notification-service
    environment:
      - APP_ENV=dev
    ports:
      - "8001:8001"
    networks:
      - monitoring
    command: ["./notification-service"]
    depends_on:
      - post-service
      - kafka
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - monitoring
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - monitoring

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
       - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "9092:9092"
    networks:
      - monitoring
  loki:
    image: grafana/loki:3.3.2
    user: "root"
    command: -config.file=/etc/loki/local-config.yaml
    volumes: [ ./data/loki:/loki ]
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:3.3.2
    command: -config.file=/etc/promtail/docker-config.yaml
    volumes:
        - ./configs/promtail.yaml:/etc/promtail/docker-config.yaml
        - /var/lib/docker/containers:/var/lib/docker/containers:ro
        - /var/run/docker.sock:/var/run/docker.sock
    depends_on: [ loki ]
    networks:
      - monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.4.0
    ports: [ "3000:3000" ]
    volumes:
      - ./configs/grafana.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    networks:
      - monitoring

# Лучше убрать из билда и запускать в ручную, так как после запуска у нас остаються тестовые данные
#  bombardier:
#    image: alpine/bombardier
#    command: [
#      "-c", "100",
#      "-d", "10s",
#      "-m", "POST",
#      "-H", "Content-Type: application/json",
#      "-b", '{"title":"Test","author":"Bombardier","content":"Test content","tags":["test"]}',
#      "http://post-service:8000/posts"
#    ]
#    networks:
#      - monitoring
#    depends_on:
#      - post-service

volumes:
  postgres_data:

networks:
  monitoring:
    driver: bridge
