name: CI Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25' 

      - name: Create .env files
        run: |
          # Создаем контент файла (используем одинаковые данные для всех сервисов)
          ENV_CONTENT="POSTGRES_USER=ivan
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB=postgres
          DB_HOST=postgres
          DB_PORT=5432
          DATABASE_URL=postgres://ivan:${{ secrets.POSTGRES_PASSWORD }}@postgres:5432/postgres?sslmode=disable"
          
          # Записываем контент в файлы каждого сервиса
          echo "$ENV_CONTENT" > ./post-service/.env
          echo "$ENV_CONTENT" > ./notification-service/.env

      - name: Build and Run
        run: |
          docker compose build
          docker compose up --abort-on-container-exit --exit-code-from notification-service
