name: CI Pipeline

on:
  push:
    branches: [ "main", "master" ] # Запускать при пуше в эти ветки
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # Укажи свою версию Go

      - name: Build Docker Compose
        run: docker-compose build

      - name: Run Tests in Docker Compose
        # Эта команда поднимет окружение, прогонит тесты и выйдет с кодом 0 или 1
        run: docker-compose up --abort-on-container-exit --exit-code-from notification-service
